# Scikit-Learn Classification

In [1]:
import numpy as np

In [4]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,1,1,1])

In [5]:
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [6]:
y

array([0, 1, 1, 1])

In [7]:
w = np.array([1,1])

In [8]:
b = -0.5

In [11]:
def activation(z):
    if z >= 0:
        return 1
    else:
        return 0

In [12]:
pred = []
for a in x:
    y_hat = np.dot(a,w)+b
    pred.append(activation(y_hat))

In [13]:
pred

[0, 1, 1, 1]

In [14]:
import math
import numpy as np

In [33]:
epochs = 100
alpha = 0.2

In [34]:
w0 = np.random.random()
w1 = np.random.random()
w2 = np.random.random()
print('Initial Weights:')
print("w0 = ",w0, "w1 = ",w1, "w2 = ",w2)

Initial Weights:
w0 =  0.6895794282798221 w1 =  0.4366457302749577 w2 =  0.4419785304941126


In [35]:
del_w0 = 1
del_w1 = 1
del_w2 = 1

In [36]:
train_data_temp = [[0,0,0], [0,0,1], [0,1,0], [0,1,1], [1,0,0], [1,0,1], [1,1,0], [1,1,1]]
train_data = np.asarray(train_data_temp)
op = np.array([0,1,1,1,1,1,1,1])

In [37]:
train_data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [38]:
op

array([0, 1, 1, 1, 1, 1, 1, 1])

In [41]:
bias = 0

In [47]:
for i in range(epochs):
    j = 0
    for x in train_data:
        y_hat = w0*x[0] + w1*x[1] + w2*x[2] + bias
        
        if (y_hat >= 0):
            act = 1
        else:
            act = 0
            
        err = op[j] - act
        
        del_w0 = alpha*x[0]*err
        del_w1 = alpha*x[1]*err
        del_w2 = alpha*x[2]*err
        
        w0 = w0 + del_w0
        w1 = w1 + del_w1
        w2 = w2 + del_w2
        
        j = j + 1
        
        print("epoch", i+1, "error = ",err)
        print(del_w0, del_w1, del_w2)
        
print("\nFinal Weights:")
print("w0 = ",w0, "w1 = ",w1, "w2 = ",w2)

epoch 1 error =  -1
-0.0 -0.0 -0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 2 error =  -1
-0.0 -0.0 -0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 3 error =  -1
-0.0 -0.0 -0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 4 error =  -1
-0.0 -0.0 -0.0
epoch 4 error =  0
0.0 0.0 0.0
epoch 4 error =  0
0.0 0.0 0.0
epoch 4 error =  0
0.0 0.0 0.0
epoch 4 error =  0
0.0 0.0 0.0
epoch 4 error =  0
0.0 0.0 0.0
epoch 4 error =  0
0.0 0.0 0.0
epoch 4 error =  0
0.0 